### ISSUE TITLE
Why different paddings were used in G()'s last down2d and first up2d?

### ISSUE THREAD

**Issue by leocnj** [hujinsen/awesome-pytorch-StarGAN-VC#1]
Thanks for sharing your useful implementation.  I have a question about Generator. Why padding (1,2) was used in the last Down2d operation while padding (0,2) was used in the first Up2d operation? Any rationale for using different paddings here?

```python
        Down2d(64, 5, (9,5), (9,1), (1,2))    # <====
        self.up1 = Up2d(9, 64, (9,5), (9,1), (0,2))
        self.up2 = Up2d(68, 128, (3,5), (1,1), (1,2))
```

**Comment by hujinsen** [comment]
Choosing which padding scheme depends on the transposed conv layer's configurations. It's clear in the figure that in README.md.
